version: "3.7"

services:
  backend:
    build: ./findus-backend
    command: bash -c /code/start.sh
    volumes:
      - ./findus-backend:/code
    restart: always

  frontend:
    build: ./findus-frontend
    volumes:
      - ./findus-frontend:/code
      - /code/node_modules
    # Workaround: https://stackoverflow.com/questions/30043872/docker-compose-node-modules-not-present-in-a-volume-after-npm-install-succeeds
    restart: always

  reverse-proxy:
    build: .
    command: nginx -g 'daemon off;'
    ports:
      - "8000:80"
      - "5000:5000"
    volumes:
      - ./findus-backend/static:/opt/app/static
    depends_on:
      - frontend
      - backend
    restart: always
