version: "3"

services:
  # django:
  #   build: ./findus-backend
  #   command: bash -c "python /code/manage.py migrate --noinput && python /code/manage.py runserver 0.0.0.0:8000"
  #   volumes:
  #     - ./findus-backend:/code
  #   ports:
  #     - "8000:8000"

  frontend:
    build: ./findus-frontend
    command: npm start
    volumes:
      - ./findus-frontend:/code
      # Workaround: https://stackoverflow.com/questions/30043872/docker-compose-node-modules-not-present-in-a-volume-after-npm-install-succeeds
      - /code/node_modules
    ports:
      - "3000:3000"
